### ISSUE TITLE
[A1 Digital International GmbH] Tracking Configuration - 10312

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#115]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-04-15 13:46:46 UTC</td></tr><tr><td>Submitter's name</td><td>Peter Gaspar</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>A1 Digital International GmbH</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Tracking Configuration</td></tr><tr><td>Object Description</td><td>Configuration parameters of a tracking device with motion sensor.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=7d15815c-8141-42e9-82b2-ad9e14f6b7d5_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/7d15815c-8141-42e9-82b2-ad9e14f6b7d5_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=7d15815c-8141-42e9-82b2-ad9e14f6b7d5_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

 - The object ID allocation for this object will be reserved as 10312
 - The object URN allocation for this object will be reserved as oma:lwm2m❌10312
 - A new branch ```digital``` has been created in the LwM2M registry for the WG to review your object

- [ ] please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/digital

Observations to be addressed
- [ ] Object version updated to 1.0
- [ ] Object ID updated to 10312
- [ ] Object urn updated to  urn:oma:lwm2m:x:10312
- [ ] The description has a spelling error I believe - ```mnotion```

Outline of steps

Steps | Actions
-- | --
1 | Submit object using the tool
2 | Staff evaluates Object. Comments added for the submitter to resolve
3 | Submitter submits a Pull Request to the nominated branch with your object
4 | Staff validates PR
5 | IPSO Working Group discuss the submitted Object registration
6 | Any issues will require the submitter to update the PR accordingly
7 | Staff validates object again after submitters updates
8 | IPSO Working Group Chair will merge the object
9 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by seanmcilroy29** [comment]
@Peter Gaspar - Please note, that for the WG to Approve this object you must submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/digital

**Comment by seanmcilroy29** [comment]
Peter Gaspar- Please note, that for the WG to Approve this object you must submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/digital

The Working Group will be holding a conf call this Thursday [20 Jun]. If no reply has been received by the 02 July the Object registration will be closed

**Comment by seanmcilroy29** [comment]
Peter Gaspar- Please note, that for the WG to Approve this object you must submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/digital

The Working Group will be holding a conf call 11 Jul. If no reply has been received for this meetingy the Object registration will be closed by the Working Group

**Comment by seanmcilroy29** [comment]
Peter Gaspar - The Working Group will be holding a conf call tomorrow, If no reply has been submitted for this meeting, the Object registration will be closed by the Working Group

**Comment by seanmcilroy29** [comment]
Issue can be closed

**Comment by jpradocueva** [comment]
@seanmcilroy29 before closing the issue, let's clean up the registry and the GitHub repo, then we can close it

**Comment by seanmcilroy29** [comment]
Issue closed due to the submission period elapsing. Submitter is requested to resubmit Object for Approval if required.
